# frozen_string_literal: true

class OrderGeneratorWorker
  include Sidekiq::Worker

  def perform(*_args)
    Order.create!(
      number: "Generated by job - #{SecureRandom.alphanumeric(5)}",
      total: rand(10..100),
      shipping_cost: 0,
      tax: 0,
      sale_channel: Order.sale_channels.values.sample,
      customer_id: 1,
      shipping_address_id: 1,
      billing_address_id: 1
    )
  end
end
