apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipyard-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: thaiduchyk/shipyard:latest
        imagePullPolicy: Always
        command: ["bundle", "exec", "puma", "-p", "3000", "-e", "staging"]
        ports:
        - containerPort: 3000

