primary_default: &primary_default
  adapter: postgresql
  host: <%=      ENV["PRIMARY_DB_HOST"] || '127.0.0.1' %>
  port: <%=      ENV["PRIMARY_DB_PORT"] || '5432' %>
  username: <%=  Rails.application.credentials.dig(:db,:primary, :username) || 'postgres' %>
  password: <%=  Rails.application.credentials.dig(:db,:primary, :password) || 'postgres' %>
  database: <%=  ENV["PRIMARY_DB_DATABASE"] || "sbtg_db_#{Rails.env}"   %>
  pool: <%=      ENV["PRIMARY_DB_POOL"] || '5' %>
  timeout: <%=   ENV["PRIMARY_DB_TIMEOUT"] || '5000' %>

legacy_default: &legacy_default
  adapter: mysql2
  host: <%=      ENV["LEGACY_DB_HOST"] || '127.0.0.1' %>
  port: <%=      ENV["LEGACY_DB_PORT"] || '3306' %>
  username: <%=  Rails.application.credentials.dig(:db, :legacy, :username) || 'root' %>
  password: <%=  Rails.application.credentials.dig(:db, :legacy, :password) || 'root' %>
  database: <%=  ENV["LEGACY_DB_DATABASE"] || 'sailboats' ||"sbtg_db_#{Rails.env}" %>
  pool: <%=      ENV["LEGACY_DB_POOL"] || '5' %>
  encoding: utf8
  reconnect: false
  #socket: /tmp/mysql.sock

development:
  primary:
    <<: *primary_default
  legacy:
    <<: *legacy_default

test:
  primary:
    <<: *primary_default
  legacy:
    <<: *legacy_default

production:
  primary:
    <<: *primary_default
  legacy:
    <<: *legacy_default
